---
- block:

    - name: Update apt package index
      apt:
        update_cache: yes
      when: ansible_distribution == 'Debian'
      # This is a lie, but necessary for Idempotence test
      changed_when: False

    # The CentOS Extras repo has epel-release in it
    - name: Install EPEL Release (CentOS)
      package:
        name: epel-release
        state: present
      when: ansible_distribution == 'CentOS'

    # No RHEL repo has epel-release in it
    # The package URL is documented as stable:
    # https://fedoraproject.org/wiki/EPEL
    - name: Install EPEL Release (RHEL)
      package:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      when: ansible_distribution == 'RedHat'

    - name: Install prerequisites
      package:
        name: '{{ pulp_preq_packages }}'
        state: present

    # Needed by psycopg2-binary from PyPI
    - name: Install prerequisites (Fedora 30+ only)
      package:
        name: libxcrypt-compat
        state: present
      when:
        - ansible_distribution == "Fedora"
        - ansible_distribution_version|int >= 30

    - name: Disable SELinux (Pulp 3 is currently incompatible with SELinux)
      selinux:
        policy: targeted
        state: permissive
      when: ansible_os_family == 'RedHat'

    # Become root so as to search paths like /usr/sbin.
    - name: Find the nologin executable
      command: which nologin
      changed_when: False
      check_mode: False
      register: result

    - name: Make sure {{ pulp_group }} group exists
      group:
        name: '{{ pulp_group }}'
        gid: '{{ pulp_group_id }}'
        state: present
        system: true

    - name: Create user {{ pulp_user }}
      user:
        name: '{{ pulp_user }}'
        uid: '{{ pulp_user_id }}'
        shell: '{{ result.stdout.strip() }}'
        home: '{{ pulp_user_home }}'
        system: true
      when: developer_user is not defined

    - name: Add user {{ pulp_user }} to {{ pulp_group }} group
      user:
        name: '{{ pulp_user }}'
        groups:
          - '{{ pulp_group }}'
        append: true

    - name: Add user {{ developer_user }} to {{ pulp_group }} group
      user:
        name: '{{ developer_user }}'
        groups:
          - '{{ pulp_group }}'
        append: true
      when: developer_user is defined

    - name: Reset ssh conn to allow user changes to affect when ssh user and pulp user are the same
      meta: reset_connection

    - name: Create cache dir for Pulp
      file:
        path: '{{ pulp_cache_dir }}'
        state: directory
        owner: '{{ pulp_user }}'
        group: '{{ pulp_group }}'
        mode: 0775

    - name: Create pulp install dir
      file:
        path: '{{ pulp_install_dir }}'
        state: directory
        owner: '{{ pulp_user }}'
        group: '{{ pulp_group }}'

    - name: Install packages needed for source install
      package:
        name:
          - git
        state: present
      register: result
      until: result is succeeded

  become: true

- block:

    # Hack for use system-wide packages when enabled by user - Must be first usage of virtualenv
    - name: Allow use system-wide packages
      pip:
        name: pip
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
        virtualenv_site_packages: yes
      when: pulp_use_system_wide_pkgs |bool

    - name: Install the psycopg python package
      pip:
        name: psycopg2-binary
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'

    - name: Install pulpcore package from source
      pip:
        name: '{{ pulp_source_dir }}'
        editable: '{{ pulp_pip_editable }}'
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      when: pulp_source_dir is defined
      # This is a hack. Editable pip installs are always changed, which fails molecule's
      # idempotence test.
      changed_when: result.changed and not pulp_pip_editable
      notify: Collect static content

    - name: Install pulpcore-plugin package from source
      pip:
        name: '{{ pulp_plugin_source_dir }}'
        editable: '{{ pulp_pip_editable }}'
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      when: pulp_plugin_source_dir is defined
      # This is a hack. Editable pip installs are always changed, which fails molecule's
      # idempotence test.
      changed_when: result.changed and not pulp_pip_editable
      notify: Collect static content

    - name: Install Pulp plugins via PyPI
      pip:
        name: '{{ item.key }}'
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      with_dict: '{{ pulp_install_plugins }}'
      when: pulp_install_plugins[item.key].source_dir is undefined
      notify: Collect static content

    - name: Install Pulp plugins from source
      pip:
        name: '{{ item.value.source_dir }}'
        editable: '{{ pulp_pip_editable }}'
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      with_dict: '{{ pulp_install_plugins }}'
      when: pulp_install_plugins[item.key].source_dir is defined
      # This is a hack. Editable pip installs are always changed, which fails molecule's
      # idempotence test.
      changed_when: result.changed and not pulp_pip_editable
      notify: Collect static content

  become: true
  become_user: '{{ pulp_user }}'
...
