---
# Upstream is slow to accept pull requests.
# Still waiting on the original " Add Fedora support" pull request from ehelms.
#
# https://github.com/geerlingguy/ansible-role-postgresql/compare/master...dralley:master
- src: https://github.com/dralley/ansible-role-postgresql
  version: master
  name: geerlingguy.postgresql

- src: https://github.com/pulp/pulp-rpm-prerequisites
  version: master
  name: pulp.pulp-rpm-prerequisites
