---
# Options
pulp_devel_supplement_bashrc: true
pulp_default_admin_password: password

pulp_user: "pulp"
developer_user: "{{ ansible_user_id }}"
developer_user_home: "{{ ansible_user_dir }}"
pulp_source_dir: "{{ developer_user_home }}/devel/pulpcore"

# Undocumented variable. Pulp will be installed from the source dir
# but to the site-packages path.
pulp_editable_mode: False

pulp_install_plugins:
  # pulp-ansible:
  #   source_dir: "/home/vagrant/devel/pulp_ansible"
  pulp-certguard:
    source_dir: "{{ developer_user_home }}/devel/pulp-certguard"
  # pulp-cookbook:
  #   source_dir: "/home/vagrant/devel/pulp_cookbook"
  # pulp-deb:
  #   source_dir: "/home/vagrant/devel/pulp_deb"
  pulp-container:
    source_dir: "{{ developer_user_home }}/devel/pulp_container"
  # pulp-gem:
  #   source_dir: "/home/vagrant/devel/pulp_gem"
  # pulp-maven:
  #   source_dir: "/home/vagrant/devel/pulp_maven"
  # pulp-python:
  #   source_dir: "/home/vagrant/devel/pulp_python"
  pulp-rpm:
    source_dir: "{{ developer_user_home }}/devel/pulp_rpm"
  pulp-file:
    source_dir: "{{ developer_user_home }}/devel/pulp_file"

pulp_settings:
  secret_key: "unsafe_default"
  content_origin: "http://{{ ansible_fqdn }}"
  # Must leave out the protocol here
  token_server: "{{ ansible_fqdn }}/token"
  token_signature_algorithm: 'ES256'
  public_key_path: '/etc/pulp/public_key.pem'
  private_key_path: '/etc/pulp/private_key.pem'
  allowed_import_paths:
    - "/tmp"
  allowed_export_paths:
    - "/tmp"
