---
- hosts: all
  vars:
    delete: false
  pre_tasks:
    # The version string below is the highest of all those in roles' metadata:
    # "min_ansible_version". It needs to be kept manually up-to-date.
    - name: Verify Ansible meets min required version
      assert:
        that: "ansible_version.full is version_compare('2.8', '>=')"
        msg: >
          "You must update Ansible to at least 2.8 to use this version of Pulp 3 Installer."

    - block:

        - command: systemctl stop pulpcore*

        - name: Reload systemd
          systemd:
            daemon_reload: true
          become: true

        - file:
            path: /usr/local/lib/pulp
            state: absent

        - file:
            path: /var/lib/pulp
            state: absent

      become: true
      when: delete

    # These user tasks are copied from pulp_common/tasks/install.yml
    - block:

        # Become root so as to search paths like /usr/sbin.
        - name: Find the nologin executable
          command: which nologin
          changed_when: False
          check_mode: False
          register: result

        - name: Make sure {{ pulp_group }} group exists
          group:
            name: '{{ pulp_group }}'
            gid: '{{ pulp_group_id }}'
            state: present
            system: true

        # If we do not create it here, but it is separate from developer_user,
        # the following task would create it incorrectly with default settings.
        - name: Create user {{ pulp_user }}
          user:
            name: '{{ pulp_user }}'
            uid: '{{ pulp_user_id }}'
            shell: '/bin/bash'
            home: '{{ pulp_user_home }}'
            system: true
            group: '{{ pulp_group }}'
            groups:
              - '{{ pulp_group }}'
            append: true
          # The check implicitly does an or for this check:
          # developer_user is not defined
          when: pulp_user != developer_user|default('')

        - name: Add user {{ pulp_user }} to extra groups
          user:
            name: '{{ pulp_user }}'
            groups: '{{ pulp_extra_groups }}'
            append: true
          when: pulp_extra_groups is defined

        - name: Add user {{ developer_user }} to {{ pulp_group }} group
          user:
            name: '{{ developer_user }}'
            groups:
              - '{{ pulp_group }}'
            append: true
          when: developer_user is defined

      become: true

    - name: Include vars after running setup
      include_vars: selinux.dev-config.yml

    - name: Create devel dir
      file:
        path: "{{ developer_user_home }}/devel"
        state: directory
        mode: 0777
        owner: "{{ developer_user }}"
      become: true
      become_user: '{{ developer_user }}'

    # So that pip can install from it
    - name: Make devel parent dir accessible to the pulp user
      file:
        path: "{{ developer_user_home }}"
        state: directory
        mode: 0755
      become: true
      become_user: '{{ developer_user }}'

    - name: Install git
      package:
        name: git
      become: true

    # Cloning all of them (rather than VCS URLs) facilitates running tests
    - name: get git repos
      git:
        repo: "https://github.com/pulp/{{ item.name }}.git"
        dest: "{{ developer_user_home }}/devel/{{ item.name }}"
        umask: "000"
        version: "{{ item.version }}"
      with_items: "{{ selinux_dev_git_repos }}"
      become: true
      become_user: '{{ developer_user }}'

    - name: Create venv for tests
      pip:
        #name: '{{ developer_user_home }}/devel/{{ item.name }}'
        name: '{{ item.name }}-client=={{ item.version }}'
        #editable: true
        state: present
        virtualenv: '{{ developer_user_home }}/devel/venv'
        #virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      with_items: "{{ selinux_dev_git_repos }}"
      become: true
      become_user: '{{ developer_user }}'

    - name: install test requirements for plugins
      pip:
        requirements: '{{ item.value.source_dir }}/test_requirements.txt'
        state: present
        virtualenv: '{{ developer_user_home }}/devel/venv'
        #virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      with_dict: '{{ pulp_install_plugins }}'
      when: pulp_install_plugins[item.key].source_dir is defined
      become: true
      become_user: '{{ developer_user }}'

    - name: install content plugins for tests
      pip:
        name: '{{ item.name }}=={{ item.version }}'
        state: present
        virtualenv: '{{ developer_user_home }}/devel/venv'
        #virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      with_items: "{{ selinux_dev_git_repos }}"
      become: true
      become_user: '{{ developer_user }}'

  post_tasks:

    - name: install optional server-side package for pulp-certguard
      pip:
        name: 'rhsm'
        state: present
        virtualenv: '{{ pulp_install_dir }}'
        virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
      become: true
      become_user: '{{ pulp_user }}'

#    - name: Create bindings install script
#      blockinfile:
#        path: "{{ developer_user_home }}/devel/bindings.sh"
#        mode: 0777
#        create: true
#        insertbefore: BOF
#        block: |
#          shopt -s expand_aliases
#          source ~/.bashrc.d/venv.bashrc
#          source ~/.bashrc.d/alias.bashrc
#          pbindings pulpcore python
#      become: true
#      become_user: '{{ developer_user }}'
#
#    - name: Populate plugins in bindings install script
#      lineinfile:
#        path: "{{ developer_user_home }}/devel/bindings.sh"
#        mode: 0777
#        create: true
#        line: "pbindings {{ item.key|replace('-','_') }} python"
#      with_dict: "{{ pulp_install_plugins }}"
#      when: pulp_install_plugins[item.key].source_dir is defined
#      become: true
#      become_user: '{{ developer_user }}'

    - name: Create functional tests script
      lineinfile:
        path: "{{ developer_user_home }}/devel/tests.sh"
        mode: 0777
        create: true
        insertbefore: BOF
        line: "cd {{ pulp_source_dir }} && pytest -v -r sx --color{{ '=' }}yes --pyargs pulpcore.tests.functional"
      become: true
      become_user: '{{ developer_user }}'

    - name: Populate plugins in functional tests script
      lineinfile:
        path: "{{ developer_user_home }}/devel/tests.sh"
        mode: 0777
        create: true
        line: "cd {{ item.value.source_dir }} && pytest -v -r sx --color{{ '=' }}yes --pyargs {{ item.key|replace('-','_') }}.tests.functional"
      with_dict: "{{ pulp_install_plugins }}"
      when: pulp_install_plugins[item.key].source_dir is defined
      become: true
      become_user: '{{ developer_user }}'

  roles:
    - gzm55.smart_ssh_pipelining
    - pulp_all_services
    - pulp_devel
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
