---
# Options
pulp_devel_supplement_bashrc: true
pulp_default_admin_password: password

pulp_user: "pulp"
developer_user: "pulp"
developer_user_home: "/var/lib/pulp"
#pulp_source_dir: "{{ developer_user_home }}/devel/pulpcore"

# Undocumented variable. Pulp will be installed from the source dir
# but to the site-packages path.
pulp_editable_mode: False

pulp_api_bind: "0.0.0.0:24817"
pulp_content_bind: "0.0.0.0:24816"

pulp_install_plugins:
  # pulp-ansible:
  #   source_dir: "/home/vagrant/devel/pulp_ansible"
  pulp-certguard:
    version: "1.0.1"
  #  source_dir: "{{ developer_user_home }}/devel/pulp-certguard"
  # pulp-cookbook:
  #   source_dir: "/home/vagrant/devel/pulp_cookbook"
  # pulp-deb:
  #   source_dir: "/home/vagrant/devel/pulp_deb"
  pulp-container:
    version: "2.0.0b3"
  #  source_dir: "{{ developer_user_home }}/devel/pulp_container"
  # pulp-gem:
  #   source_dir: "/home/vagrant/devel/pulp_gem"
  # pulp-maven:
  #   source_dir: "/home/vagrant/devel/pulp_maven"
  # pulp-python:
  #   source_dir: "/home/vagrant/devel/pulp_python"
  pulp-rpm:
    version: "3.4.2"
  #  source_dir: "{{ developer_user_home }}/devel/pulp_rpm"
  pulp-file:
  #  source_dir: "{{ developer_user_home }}/devel/pulp_file"
    version: "1.1.0"

pulp_settings:
  secret_key: "unsafe_default"
  content_origin: "http://{{ ansible_fqdn }}"
  # Must leave out the protocol here
  token_server: "http://{{ ansible_fqdn }}/token"
  token_signature_algorithm: 'ES256'
  public_key_path: '/etc/pulp/public_key.pem'
  private_key_path: '/etc/pulp/private_key.pem'
  allowed_import_paths:
    - "/tmp"
  allowed_export_paths:
    - "/tmp"

selinux_dev_git_repos:
  - { name: "pulpcore", version: "3.5.0" }
  - { name: "pulp_file", version: "1.1.0" }
  - { name: "pulp_container", version: "2.0.0b3" }
  - { name: "pulp_rpm", version: "3.4.2" }
  - { name: "pulp-certguard", version: "1.0.1" }
