---
- block:

    - name: Install firewalld
      package:
        name: firewalld
        state: present

    - name: Start and enable firewalld
      systemd:
        name: firewalld
        state: started
        enabled: true
      register: firewalld_service

    # Workaround dbus ServiceUnknown error in firewalld module.
    # Observed on CentOS 7.7, but is an issue in general.
    # https://github.com/dw/mitogen/issues/570#issuecomment-475754758
    - name: Reset connection
      meta: reset_connection
      when: firewalld_service.changed

    - name: Accept connections on port 80
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled

  become: true
