---
- name: Get services
  service_facts:

- name: Listing Pulp services
  debug:
    msg: '{{ ansible_facts.services|dict2items|selectattr("key", "contains", "pulp")|list|items2dict }}'

- name: Reset variable
  set_fact:
    __service_check_success: true

- name: Checking Pulp services
  set_fact:
    __service_check_success: false
  when: "item.value.name != 'pulpcore-worker@.service' and item.value.state != 'running'"
  with_dict: '{{ ansible_facts.services|dict2items|selectattr("key", "contains", "pulp")|list|items2dict }}'

