---
- name: Verify
  hosts: all
  tasks:
    - name: Print some debug information
      vars:
        msg: |
          Module Variables ("vars"):
          --------------------------------
          {{ vars | to_nice_json }}

          Environment Variables ("environment"):
          --------------------------------
          {{ environment | to_nice_json }}

          GROUP NAMES Variables ("group_names"):
          --------------------------------
          {{ group_names | to_nice_json }}

          GROUPS Variables ("groups"):
          --------------------------------
          {{ groups | to_nice_json }}

          HOST Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_json }}

      debug:
        msg: "{{ msg.split('\n') }}"
      tags: debug_info
    - name: Get status page
      uri:
        url: "http://localhost/pulp/api/v3/status/"
        return_content: true
      register: status_page

    - debug:
        msg: "{{ status_page.content }}"
