---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
# This is ignored by molecule, but can be reused in yaml
.platform_base: &platform_base
  privileged: False
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  tmpfs:
    - /tmp
    - /run
    - /run/lock
  capabilities:
    - NET_ADMIN
    - NET_RAW
platforms:
  - <<: *platform_base
    name: centos-7
    image: centos:7
    command: /sbin/init
  - <<: *platform_base
    name: fedora-31
    image: fedora:31
    command: /usr/sbin/init
provisioner:
  name: ansible
  inventory:
    links:
      host_vars: ../scenario_resources/host_vars/
      group_vars: ../scenario_resources/group_vars/
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
verifier:
  name: inspec
  lint:
    name: rubocop
    enabled: false
