---
- name: include_tasks to build Galaxy WebUI if galaxy-ng is among the plugins
  include_tasks:
    file: galaxy_ui.yml
    apply:
      become: true
  when: pulp_install_plugins_normalized['galaxy-ng'] is defined

- import_tasks: install_basic_packages.yml
  become: true

- name: "Add {{ pulp_user }} to systemd-journal group"
  user:
    name: "{{ pulp_user }}"
    groups: systemd-journal
    append: yes
  become: true

- import_tasks: install_podman.yml
  become: true

- import_tasks: install_docs_requirements.yml
  become: true
  become_user: '{{ pulp_user }}'

- import_tasks: bashrc.yml
  become: true
  become_user: "{{ developer_user }}"

- import_tasks: config_files.yml
  become: true
  become_user: "{{ developer_user }}"

- name: check if pulp_rpm exists on disk
  stat:
    path: "{{ developer_user_home }}/devel/pulp_rpm"
  register: rpm_stat

- name: include_tasks to create signing service if pulp_rpm is among the plugins
  include_tasks:
    file: rpm_signing_service.yml
    apply:
      become: true
  when:
    - pulp_install_plugins_normalized['pulp-rpm'] is defined
    - pulp_install_plugins_normalized['pulp-rpm'].source_dir is defined
      or rpm_stat.stat.exists

- name: Set the message of the day
  copy:
    src: motd
    dest: /etc/motd
  become: true
...
